### ISSUE TITLE
Add breakout for I2C, SPI, and UART on the PCB

### ISSUE THREAD

**Issue by hak8or** [hak8or/WeatherSpot#1]
For Kicad @glina126

**Comment by glina126** [comment]
will do, as well as test points.

**Comment by hak8or** [comment]
Just a cool thing, if you reference this in your commit, like

``` bash
git commit -m "Added breakouts as per issue #1"
```

then the commit will be referenced in here. :sunglasses: And if you do `fixes issue #1` then it will even close the issue!
