### ISSUE TITLE
Notify weatherspot.us when a Series has not recieved any data for 30 minutes

### ISSUE THREAD

**Issue by pl12133** [hak8or/WeatherSpot#13]
Idea is a bash script running as a cronjob every hour, checks the latest data point in a given series and if it is greater than 30 minutes old, send an email to root@weatherspot.us

Running: `./notifyNoDataInSeries Downtown`

**Comment by pl12133** [comment]
Looks like this will require me to install `mailutils` unless anyone objects.

**Comment by glina126** [comment]
Mailutils is very vulnerable from what I remember - plus we will get lots of spam. Check out a service such as zoho mail

**Comment by pl12133** [comment]
OK I didn't install mailutils because it really is overkill. We can figure out what manner of notifications we want to receive later.

[Here](https://gist.github.com/pl12133/2d645b9346ef9b253bfa) is a bash script that tells us how long it has been since a series has been updated.
Whatever mechanism we choose to trigger when a series is not receiving updates can use this script. This script can be found in `~/scripts` on our webserver.
