### ISSUE TITLE
Heartbeat - messes up light readings

### ISSUE THREAD

**Issue by glina126** [hak8or/WeatherSpot#15]
The heartbeat, as great as it is, it is working against us here. 

1, its using power - not much, but still. three hour battery life is not too long... 
2. it is offsetting the light measurements. 

Solution:
- reduce the blink rate
- blink only when not measuring the light intensity

**Comment by hak8or** [comment]
The power consumption of heart beat is very low. I wouldn't even think about power consumption untill we can put the wifi module to sleep.

But what we could do is actually have it blink maybe once every 5 seconds with a 5% duty cycle or something like that. The chances of the light reading happening while the LED is active is 5% which is pretty small. Or continue at the speed now but make the duty cycle much smaller which would lead the same result.

**Comment by glina126** [comment]
I am trying out disconnecting the wifi module from the AP, I will run a test to see if that helps preserve power.

**Comment by hak8or** [comment]
Meaning the `AT+CWQAP` command? Did you try out the sleep command yet with the soldering fix?

Also, for sleep, to save you googling, it's `AT+GSLP=500` to make it sleep 500 milliseconds and then wake up by itself and start the ESP module again from scratch (just like after a reset state). But you have to solder "XPD_DCDC with EXT_RSTB via 0R" for this to work.

**Comment by glina126** [comment]
yea i am doing the CT+CWQAP command for now. I will see how long this lives first. then I will try the AT+GSLP command - I really dont want to mess with soldering on the unit.

**Comment by hak8or** [comment]
Soldering would be just shorting one of [these two pads](https://goo.gl/photos/3yqcSUxmTnHtEDG38) though (SMD module).

**Comment by hak8or** [comment]
Alright, so I just flashed my board with the new firmware and will let it run for an hour and see how the light readings are. If it's good, I guess we can close this.

**Comment by hak8or** [comment]
Closed since the heartbeat led is now disabled during sensor readings.
