### ISSUE TITLE
Locations.html doesnt work properly

### ISSUE THREAD

**Issue by glina126** [hak8or/WeatherSpot#18]
locations.html has very strange spacing and it does not clear the old graphs when you switch to a new one. Instead it appends more and more graphs on the bottom with huge spacing.

**Comment by pl12133** [comment]
That sounds like a broken version that I was working on but it has since been fixed, can you make sure that's not a cached copy? It was unstable like that before but `locations.html` should be working now.

**Comment by hak8or** [comment]
Working totally fine on my end when mobile. I never noticed any spacing issues earlier, or that graphs were appended instead of replaced for locations.html

**Comment by pl12133** [comment]
Fixed.
