### ISSUE TITLE
Put API on mashape

### ISSUE THREAD

**Issue by ple1213** [hak8or/WeatherSpot#7]

**Comment by pl12133** [comment]
https://www.mashape.com/pl12133/weatherspot

This is the beginning of the API documentation, I will continue improving it as we go along

**Comment by hak8or** [comment]
Seems to be down? Mashape is saying that the API is not found.

**Comment by pl12133** [comment]
Looks like Mashape is telling me the API and my user account have been deactivated, and the whole website in general isn't loading for me. The whole website is now a bunch of loading icons that never load.

**Comment by pl12133** [comment]
My login works but "It seems that the API owner has removed the API from the Mashape public marketplace" so all my documentation got wiped.

**Comment by pl12133** [comment]
https://www.mashape.com/pl12133/weatherspot/

Once again it is up. I did it as fast as possible because if they deleted it last time it could happen again.
